instahyre:
  username: your-email@example.com
  password: your-password

  keywords:
    - Java
    - Python
    - JavaScript
    - TypeScript
    - C++
    - C#
    - Node.js
    - Algorithms
    - Data Structures
    - Cloud
    - Spring Boot
    - Microservices
    - REST API
    - MySQL
    - MongoDB
    - Kafka
    - RabbitMQ
    - PostgreSQL
    - Docker
    - Kubernetes
    - AWS
    - GCP
    - Azure

  use-manual-cookies: true
  sessionid: "YOUR_SESSION_ID"
  csrftoken: "YOUR_CSRF_TOKEN"

  # Job search config
  job-search:
    enabled: true
    skills:
      - Java
      - Spring Boot
      - AWS
      - GCP
      - SQL
      - RabbitMQ
      - Kafka
      - Docker
      - Kubernetes
  location:
    - "Work From Home"
    - "North India"
    - "Delhi / NCR"
    - "Bangalore"
    - "Hyderabad"
    - "Dubai"
    - "United Arab Emirates (UAE)"
    - "Qatar"
    - "Saudi Arabia"
    - "Oman"
    - "Anywhere in Uttar Pradesh"
  years-of-experience: 3

spring:
  application:
    name: instahyre-auto-applier
  devtools:
    restart:
      enabled: false    # ‚Üê CRITICAL: stops duplicate runs
    add-properties: false

spring.task.scheduling.enabled: true

logging:
  level:
    com.example.demo: INFO
    org.openqa.selenium: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"